/** Slugs that have animated illustrations instead of screenshot placeholders. */
export const animatedSlugs = new Set([
  "order-tracking",
  "wholesale",
  "crm",
  "invoices",
  "product-management",
  "email-campaigns",
  "social-scheduling",
  "content-calendar",
  "embedded-forms",
  "green-bean-inventory",
  "inventory-tracking",
  "roast-log",
  "production-planner",
  "cupping-scorecards",
  "calculators",
  "certifications",
  "dashboard",
  "analytics",
  "inbox",
  "integrations",
  "help-center",
  "ai",
]);
